server:
  port: 4001
spring:
  cloud:
    consul:
      host: localhost
      discovery:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/follow_db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
  application:
    name: FollowMS
    
     